// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAwfUxejM7i9DRg_H6iW82fLfT4ArUeO2M',
//     appId: '1:90968475269:web:7e73fbdecb44b069d10bec',
//     messagingSenderId: '90968475269',
//     projectId: 'follproject',
//     authDomain: 'follproject.firebaseapp.com',
//     storageBucket: 'follproject.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA9qP_EbAywbl0scq0G_CSIGRPpIdBtGzU',
//     appId: '1:90968475269:android:0d937a119355f35dd10bec',
//     messagingSenderId: '90968475269',
//     projectId: 'follproject',
//     storageBucket: 'follproject.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAFRwKJ6k8YWf15fYM_6YW1D5RBAnZmZUg',
//     appId: '1:90968475269:ios:ee45f719b26eddd8d10bec',
//     messagingSenderId: '90968475269',
//     projectId: 'follproject',
//     storageBucket: 'follproject.appspot.com',
//     iosBundleId: 'com.example.fluttercode',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAFRwKJ6k8YWf15fYM_6YW1D5RBAnZmZUg',
//     appId: '1:90968475269:ios:ee45f719b26eddd8d10bec',
//     messagingSenderId: '90968475269',
//     projectId: 'follproject',
//     storageBucket: 'follproject.appspot.com',
//     iosBundleId: 'com.example.fluttercode',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAwfUxejM7i9DRg_H6iW82fLfT4ArUeO2M',
//     appId: '1:90968475269:web:1f3388527e60505cd10bec',
//     messagingSenderId: '90968475269',
//     projectId: 'follproject',
//     authDomain: 'follproject.firebaseapp.com',
//     storageBucket: 'follproject.appspot.com',
//   );
// }
