name: Prontas
description: App para gestantes!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.3
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  typed_data: ^1.3.2
  html: ^0.15.4
  flutter_snake_navigationbar: ^0.6.1

  shimmer: ^3.0.0
  url_launcher: ^6.0.20
  flutter_custom_tabs: ^2.1.0
  zego_uikit_prebuilt_live_streaming: ^3.13.12
  zego_express_engine: ^3.17.0
  video_player: ^2.9.2
  youtube_player_iframe: ^4.0.4
  youtube_player_flutter: ^9.1.1
  carousel_slider: ^5.0.0
  qr_code_scanner_plus: ^2.0.10+1




  





# dart run flutter_native_splash:create



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/illustrator/illustrator1.png
    - assets/images/illustrator/illustrator2.png
    - assets/images/logo/image.png


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf